In [1]:
import pandas as pd

In [2]:
df  = pd.read_csv('../datasets/BankNoteAuthentication.csv')

In [3]:
df

variance  skewness  curtosis  entropy  class
0      3.62160   8.66610   -2.8073 -0.44699      0
1      4.54590   8.16740   -2.4586 -1.46210      0
2      3.86600  -2.63830    1.9242  0.10645      0
3      3.45660   9.52280   -4.0112 -3.59440      0
4      0.32924  -4.45520    4.5718 -0.98880      0
...        ...       ...       ...      ...    ...
1367   0.40614   1.34920   -1.4501 -0.55949      1
1368  -1.38870  -4.87730    6.4774  0.34179      1
1369  -3.75030 -13.45860   17.5932 -2.77710      1
1370  -3.56370  -8.38270   12.3930 -1.28230      1
1371  -2.54190  -0.65804    2.6842  1.19520      1

[1372 rows x 5 columns]

In [4]:
x = df[['variance','skewness','curtosis','entropy']]

In [5]:
x.shape

(1372, 4)

In [6]:
from sklearn.decomposition import PCA

In [7]:
pca = PCA(n_components=2)

In [8]:
x_new = pca.fit_transform(x)

In [9]:
x_new.shape

(1372, 2)

In [10]:
(x_new)

array([[-8.11795423, -2.37261472],
       [-7.80012416, -2.68955497],
       [ 3.69019492, -4.37272011],
       ...,
       [21.7274316 ,  4.87011432],
       [14.94631025,  3.83231438],
       [ 3.56524732,  1.03212035]])

In [11]:
pca.explained_variance_

array([49.88014585,  9.2972722 ])

In [12]:
pca.components_

array([[-0.14102363, -0.81039291,  0.54974221,  0.14546192],
       [-0.80185963,  0.263574  ,  0.30038199, -0.44420777]])

In [16]:
x_centered = x-x.mean()

In [17]:
x_centered.mean()

variance    6.946177e-16
skewness   -2.286153e-15
curtosis   -1.323528e-15
entropy    -7.664747e-16
dtype: float64

In [19]:
mat = x_centered.cov()

In [20]:
mat

variance   skewness   curtosis   entropy
variance  8.081299   4.405083  -4.666323  1.653338
skewness  4.405083  34.445710 -19.905119 -6.490033
curtosis -4.666323 -19.905119  18.576359  2.887241
entropy   1.653338  -6.490033   2.887241  4.414256

In [21]:
import numpy as np

In [22]:
eig_val,eig_vec =  np.linalg.eig(mat)

In [23]:
eig_val

array([49.88014585,  9.2972722 ,  1.94936791,  4.39083842])

In [24]:
eig_vec

array([[ 0.14102363,  0.80185963,  0.38873816,  0.43129585],
       [ 0.81039291, -0.263574  , -0.25638111,  0.45613683],
       [-0.54974221, -0.30038199, -0.04435204,  0.77819474],
       [-0.14546192,  0.44420777, -0.88384629,  0.01833097]])

In [28]:
np.dot(x_centered,eig_vec[0:2,:].T)

array([[ 4.54365855,  2.22368034],
       [ 3.97185956,  2.55174171],
       [-2.40840625,  4.44066345],
       ...,
       [-7.31137111, -4.21211124],
       [-4.59171198, -3.38370083],
       [-0.95916665, -0.97242899]])